### ISSUE TITLE
Container App: Testfairy SDK

### ISSUE THREAD

**Issue by aaron-furtado-wwindia** [sharewater-dev/AARescue#23]
## Requirement
Integrate the TestFairy plugin for testing.

## Understanding
Integrate and set up the project for using TestFairy during testing.

## Dependencies
[`com.testfairy.cordova-plugin`](https://docs.testfairy.com/Platforms/Ionic.html)

## Development & Execution
- [x] integrate `com.testfairy.cordova-plugin` plugin
- [x] implement TestFairy and initailize it.
- [ ] add API key from TestFairy to enable app for testing using TestFairy.

## Branches

`development` ➡️  `testfairy-sdk`

**Comment by aaron-furtado-wwindia** [comment]
@sharewater-dev / @evelynviljoen kindly provide API key from TestFairy account to enable the use of TestFairy within the app.

**Comment by sharewater-dev** [comment]
Your app token is:  
240cb6971373ecd2e3fe3286990daf767e8d47b0

**Comment by vaibhav-khot** [comment]
Its already implemented

**Comment by aaron-furtado-wwindia** [comment]
Okay @vaibhav-khot @sharewater-dev Let's close it.
