### ISSUE TITLE
Panic Buttonkj;lkdjfklgjlkdj

### ISSUE THREAD

**Issue by sharewater-dev** [sharewater-dev/AARescue#37]

**Comment by aaron-furtado-wwindia** [comment]
Cool I see this! 👍

**Comment by sharewater-dev** [comment]
![screenhunter 71](https://cloud.githubusercontent.com/assets/23119477/23542649/01d9d088-fff7-11e6-822f-85533d86b1cc.png)

**Comment by aaron-furtado-wwindia** [comment]
This approach works well for you @sharewater-dev ?
