### ISSUE TITLE
show custom circle loading and navigate on all input screens.

### ISSUE THREAD

**Issue by sharewater-dev** [sharewater-dev/AARescue#39]

**Comment by sharewater-dev** [comment]
![screenhunter 87](https://cloud.githubusercontent.com/assets/23119477/23543458/f866d060-fffa-11e6-9fb2-3e8eed11d7fd.png)
![screenhunter 88](https://cloud.githubusercontent.com/assets/23119477/23543470/01b7ad1a-fffb-11e6-8ba8-1475e18466f4.png)

**Comment by aaron-furtado-wwindia** [comment]
@mitul-neosoft You can reuse the loader code from the Senter360 project. Apply it to Web API calls as well.
