### ISSUE TITLE
Panic Button activation

### ISSUE THREAD

**Issue by sharewater-dev** [sharewater-dev/AARescue#41]

**Comment by sharewater-dev** [comment]
1. If user presses anywhere on this screen then it activates panic.
2. Only be able to press in the square to activate panic button
![screenhunter 91](https://cloud.githubusercontent.com/assets/23119477/23543687/f8557daa-fffb-11e6-8348-d80bebb94ed0.png)

**Comment by aaron-furtado-wwindia** [comment]
Nicely done @vaibhav-khot . That was quick. 😄
