### ISSUE TITLE
Cancelling a panic button

### ISSUE THREAD

**Issue by sharewater-dev** [sharewater-dev/AARescue#44]

**Comment by sharewater-dev** [comment]
![screenhunter 94](https://cloud.githubusercontent.com/assets/23119477/23543878/f5511500-fffc-11e6-89b0-0e1cafb8beb4.png)

**Comment by vaibhav-khot** [comment]
its actually happening ...before 5 sec time out if we cancel panic alert then it moved back to panic alert page ...

**Comment by vaibhav-khot** [comment]
and if panic alert is successful then that slider is disabled ...

**Comment by aaron-furtado-wwindia** [comment]
@vaibhav-khot I guess this is the case only when API throws an error or does not respond.
once 5 seconds are elapsed and you initiate API request, directly take user to Emergencies page.
This should solve this.
