### ISSUE TITLE
Home page changes:

### ISSUE THREAD

**Issue by sharewater-dev** [sharewater-dev/AARescue#45]

**Comment by sharewater-dev** [comment]
![screenhunter 90](https://cloud.githubusercontent.com/assets/23119477/23543961/6c6d69fe-fffd-11e6-9f81-966467d87ca2.png)

**Comment by vaibhav-khot** [comment]
can you provide emergency logo...for emergency button

**Comment by sharewater-dev** [comment]
please use ionic icon - 
warning
ios-warning
ios-warning-outline
md-warning
Usage:

 
  
  <ion-icon name="warning"></ion-icon>

  
  <ion-icon ios="ios-warning" md="md-warning"></ion-icon>

**Comment by sharewater-dev** [comment]
Please can we make the Icon a little bigger on the home screen.
