### ISSUE TITLE
Feedback: Hi there

Herewith my input:
* AA eCard gives error message?
* Reminders are confusing. Perhaps indicate reminder types first, then have screen that gives you option to insert as reminder A B C?
* Rescue button is too small, looks like a logo...

### ISSUE THREAD

**Issue by sharewater-dev** [sharewater-dev/AARescue#48]
[TestFairy session: 8](https://activatesoftware.testfairy.com/projects/4014536-aarescue/builds/5166697/sessions/8#t=30m30s) 
Description: Hi there

Herewith my input:
* AA eCard gives error message?
* Reminders are confusing. Perhaps indicate reminder types first, then have screen that gives you option to insert as reminder A B C?
* Rescue button is too small, looks like a logo only? People won't know to press it?
* Design suggestion only: upon registration, when information is entered, add an "enter" or "ok" option into the keyboard. I was not sure how to enter once completing first info, until I realized that I just need to tap on screen and press "continue". Might be confusing to other people as well?

Hope it helps.

Regards
Elitia
App: AARescue - 0.25.0 (0.25.0)
Date: 2017-03-03 05:14:41
User: elitia.viviers@aasa.co.za
Device: Apple - iPhone SE

**Comment by aaron-furtado-wwindia** [comment]
AA eCard gives error message?
> Not in scope of current app

Reminders are confusing. Perhaps indicate reminder types first, then have screen that gives you option to insert as reminder A B C?
> Not in scope of alpha

Design suggestion only: upon registration, when information is entered, add an "enter" or "ok" option into the keyboard. I was not sure how to enter once completing first info, until I realized that I just need to tap on screen and press "continue". Might be confusing to other people as well?
> Keyboard cannot be controlled/manipulated in ionic.

**Comment by sharewater-dev** [comment]
Reminder Services:
1. Drivers Licence
2. Vehicle Licence
3. Tyre Rotation
4. Vehicle service
5. Battery Replacement
6. Other
