### ISSUE TITLE
Feedback: If you want to rate the app, it takes you to a Seeff post page?

### ISSUE THREAD

**Issue by sharewater-dev** [sharewater-dev/AARescue#49]
[TestFairy session: 8](https://activatesoftware.testfairy.com/projects/4014536-aarescue/builds/5166697/sessions/8#t=31m54s) 
Description: If you want to rate the app, it takes you to a Seeff post page?
App: AARescue - 0.25.0 (0.25.0)
Date: 2017-03-03 05:16:05
User: elitia.viviers@aasa.co.za
Device: Apple - iPhone SE

**Comment by aaron-furtado-wwindia** [comment]
Client to provide more information.

**Comment by vaibhav-khot** [comment]
this was what the client has specified to redirect the page ..
