### ISSUE TITLE
Feedback: App crashes

### ISSUE THREAD

**Issue by sharewater-dev** [sharewater-dev/AARescue#62]
[TestFairy session: 9](https://activatesoftware.testfairy.com/projects/3885456-aarescue/builds/5219719/sessions/9#t=07m53s) 
Description: App crashes
App: AARescue - 0.27.0 (2700)
Date: 2017-03-08 01:40:28
User: evelyn@sharewater.co.za
Device: Samsung - Galaxy S5
<br/>![](https://s3.amazonaws.com/testfairy//feedback_screenshots/131561/e56cbcbf0a6520750816ea5d0d1d7725e5f04818.jpg)

**Comment by vaibhav-khot** [comment]
I check that its not crashing
