### ISSUE TITLE
All links should open in the in-app browser

### ISSUE THREAD

**Issue by aaron-furtado-wwindia** [sharewater-dev/AARescue#65]
### Screen

Terms and Conditions

### Required

All links should open in the in-app browser.

Refer image

![screen](https://cloud.githubusercontent.com/assets/22975829/23751279/a551ffb6-04f6-11e7-84c2-fd81c9745503.png)

### Requested by

@sharewater-dev 

### TODO

To launch all URLs using in-app browser.

**Comment by vaibhav-khot** [comment]
Completed
