### ISSUE TITLE
AA eCard button: Launch AAeCard app

### ISSUE THREAD

**Issue by aaron-furtado-wwindia** [sharewater-dev/AARescue#67]
### Screen

Home Dashboard

### Required

AA eCard button: Launch AAeCard app.

Refer image

![screen](https://cloud.githubusercontent.com/assets/22975829/23754369/b03c9240-0502-11e7-8c7d-483928771a0f.png)

### Requested by

@sharewater-dev 

### TODO

Launch AA eCard app

**Comment by vaibhav-khot** [comment]
completed
