### ISSUE TITLE
"Coming Soon" message to be displayed

### ISSUE THREAD

**Issue by aaron-furtado-wwindia** [sharewater-dev/AARescue#68]
### Screen

Side menu

### Required

"Coming Soon" message to be displayed on click of the following:
Messages
Contacts
Rate App

Refer image
![screen](https://cloud.githubusercontent.com/assets/22975829/23754575/851e3d2e-0503-11e7-9474-3b9d511f38d0.png)

### Requested by

@sharewater-dev 

### TODO

Display toast with message "Coming Soon"

**Comment by mitul-neosoft** [comment]
Completed
