### ISSUE TITLE
FAQ, T&C: open in app browser

### ISSUE THREAD

**Issue by aaron-furtado-wwindia** [sharewater-dev/AARescue#69]
### Screen

Side menu

### Required

FAQ, T&C: open in app browser

Refer image
![screen](https://cloud.githubusercontent.com/assets/22975829/23754818/5ee441a2-0504-11e7-8c4f-037995662427.png)

### Requested by

@sharewater-dev 

### TODO

FAQ, T&C: launch in app browser instead of external browser

**Comment by vaibhav-khot** [comment]
included in issue #65 changes
