### ISSUE TITLE
Your Details Screen

### ISSUE THREAD

**Issue by aaron-furtado-wwindia** [sharewater-dev/AARescue#79]
### Screen

Accident Assist

### Required

Implement Screen
Add "Back" button to go to the previous screen.
"Save and Continue" to save data in respective Cloudbanc Docmument and RS web APIs then open "3rd Party Details" Screen

Refer screen

![your details](https://cloud.githubusercontent.com/assets/22975829/23786425/086d86aa-0593-11e7-845b-ce3b532439c7.jpg)

### Requested by

@sharewater-dev 

### TODO

- [x] Add back button to pop current screen
- [x] Navigate to "3rd Party Details"

**Comment by vaibhav-khot** [comment]
completed
